name: code-scanning
on:
  push:
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip
      - run: pip install -e ".[analysis]"
      - run: python -c "import os; os.makedirs('.speckit/analysis', exist_ok=True)"
      - run: specify audit --path . --output sarif --fail-on HIGH || true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .speckit/analysis/report.sarif
