name: Coverage

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[analysis,reporting,dev]"

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=term-missing --cov-report=xml

      - name: Enforce coverage threshold
        run: |
          python -c "
          import sys, xml.etree.ElementTree as ET
          pct = float(ET.parse('coverage.xml').getroot().attrib['line-rate']) * 100
          print(f'Coverage: {pct:.2f}%')
          sys.exit(0 if pct >= 70.0 else 1)
          "
